client/socket.js, client/whiteboard.js, public/style.css, server/socket/index.js
=> Merged boilermaker and whiteboard

package-lock.json, package.json, server/db/db.js, server/db/models/game.js, server/db/models/index.js, server/db/models/room.js, server/db/models/word.js
=> created models for Room Game Words

client/components/game/Create.js, client/components/game/Home.js, client/components/game/Play.js, client/routes.js
=> Fixed routes/rendering for components

client/components/guesser.js, client/components/reactWhiteboard.js, client/routes.js, server/socket/index.js
=> React whiteboard sockets

client/components/guesser.js, client/components/reactWhiteboard.js, server/socket/index.js
=> Potentially fixed socket

client/components/reactWhiteboard.js
=> FIXED SOCKETS

client/components/game/Create.js, client/components/game/Main.js, client/store/allRoom.js, server/api/room.js
=> finished creating the post request

client/components/game/AllRoom.js, client/components/game/Play.js, client/components/game/Room.js, client/store/allRoom.js, client/store/allUsers.js, server/api/room.js, server/api/users.js
=> New nav branch

client/components/game/FindRoom.js
=> merge bugfixing

client/components/game/AllPlayers.js, client/components/game/FindRoom.js, client/components/game/Play.js, client/store/allRoom.js, package-lock.json, server/api/room.js
=> Users in room

client/components/game/AllRooms.js, client/components/game/Play.js, client/store/allRoom.js, public/style.css, server/api/room.js
=> added associate and disassociate from room functionality

client/components/game/Play.js, client/components/guesser.js, client/components/reactWhiteboard.js
=> hardcoded demo

client/components/game/Play.js, client/components/reactWhiteboard.js, package-lock.json, package.json
=> Added Eraser and Clear

script/seed.js
=> added Picasso for testing

client/components/game/AllPlayers.js, public/style.css
=> added formatting to lobby view

client/components/game/Lobby.js, server/socket/index.js
=> Incomplete Routing to Game

client/components/Artist.js, client/components/game.js, client/components/game/Lobby.js, client/components/guesser.js, server/socket/index.js
=> Refactored Sockets + Updated Bootstrap

client/components/Artist.js, client/components/auth-form.js, client/components/game.js, client/components/game/AllRooms.js, client/components/game/Create.js, client/components/game/FindRoom.js, client/components/game/Lobby.js, client/components/guesser.js, server/api/users.js
=> Fixed routing and create

client/components/game/Create.js
=> fixed create reroute issue grabbing new lobby's id now

client/components/game/Create.js
=> fixed bug in create component was routing sending user not room

client/components/game/Lobby.js, server/socket/index.js
=> fixed issue navigating to room and back breaking

client/components/Artist.js, client/components/chatroom.js, client/components/game.js, client/components/game/Lobby.js, client/components/guesser.js
=> Miscchanges

client/components/Artist.js, client/components/guesser.js, package-lock.json, package.json, server/socket/index.js
=> Whiteboard css touchups

client/components/game/AllRooms.js, client/components/game/Lobby.js, client/store/allRoom.js, server/api/room.js
=> fixed redirect and redux issues added initial pass paintbrush logic

client/components/chatroom.js, client/components/game/AllRooms.js, client/components/game/Lobby.js, client/store/allRoom.js
=> user rendering works

client/components/chatroom.js, client/components/game/Lobby.js, server/socket/index.js
=> Pass the paintbrush working mostly

client/components/auth-form.js, client/components/game/Main.js, public/style.css
=> added rainbow color to the sub header

client/components/Artist.js, client/components/chatroom.js, client/components/game/Lobby.js, client/components/guesser.js, public/style.css
=> Minor Fixes

client/components/chatroom.js, client/components/game/Lobby.js, public/style.css
=> Updated chat

client/components/chatroom.js, client/components/game/AllRooms.js, public/style.css
=> Updated CSS for Whiteboard

client/components/Artist.js, client/components/guesser.js, package-lock.json, package.json, public/style.css, webpack.config.js
=> toasts added, artist and guesser view CSS fixed

client/components/chatroom.js, client/components/game.js, client/components/game/Create.js, client/components/game/Lobby.js, client/components/guesser.js, public/style.css
=> Chatroom bugs

client/components/CreateLobby.js, client/routes.js, public/style.css
=> fixed some bugs

client/components/chatroom.js
=> chat now autoscrolls to bottom on new message

client/components/CreateLobby.js, client/components/FindRoom.js, client/components/Lobby.js, server/socket/index.js
=> Live room view refresh

client/components/AllRooms.js, client/components/Artist.js, client/components/CreateLobby.js, client/components/FindRoom.js, client/components/LoginPage.js, client/components/MainPage.js, client/components/UserHome.js, client/components/guesser.js, public/style.css
=> Responsive Sizing, INCOMPLETE WHITEBOARD

client/components/Artist.js, client/components/guesser.js, server/socket/index.js
=> Artist notifications

client/components/AllRooms.js, client/components/CreateLobby.js, client/components/FindRoom.js, client/components/Instruction.js, client/components/LoginPage.js, client/components/MainPage.js, client/components/UserHome.js, public/style.css
=> Instructions

client/components/AllRooms.js, client/components/Artist.js, client/components/LoginPage.js, client/components/guesser.js, public/style.css
=> Whiteboard responsive sizing

script/seed.js
=> commented out seed file so seed only creates words list

client/store/allRoom.js
=> search room is no longer case sensitive
